name: front-deploy
description: Deploy frontend to S3 bucket
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
jobs:
  s3Deploy:
    runs-on: ubuntu-latest
    name: front-deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Clean npm cache
        run: npm cache clean --force

      - name: Installing dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Deployment build
        run: npm run build
        working-directory: ./frontend

      - name: Connecting to S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.S3_ARN_ROLE}}
          aws-region: eu-north-1

      - name: Deploy build to S3
        run: aws s3 sync ./frontend/dist ${{secrets.S3_DIR}} --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.S3_CF_ID}} --paths "/*"
